#!/bin/bash

if [ -n $CODESPACES ]
then
  echo "GITHUB_TOKEN=$(gh auth token)" > .env.gh

else
  if [ -e ".env" ]
  then
    source .env
    echo $GHCR_TOKEN | docker login ghcr.io \
      -u $(git config --get user.email) \
      --password-stdin
  else
    echo "GITHUB_TOKEN=$(gh auth token)" > .env.gh
  fi
fi